# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  南宫燚滨
subtitle: 耕耘不断，晟功在望
name: 南宫燚滨 
email: nangongyibin@gmail.com
description: 人生最幸福的四件事：有人信你、有人爱你、有人帮你、有人懂你。遇见不论早晚，真心才能相伴；朋友不论远近，懂得才有温暖。轰轰烈烈的，未必是真心；默默无声的，未必是无心。把一切交给时间，总会有答案。平淡中的相守，才最珍贵；简单中的拥有，才最心安！说的再好不如做的好。感恩生命中信我、爱我、懂我、帮我的人。
keywords: 南宫燚滨,Android,
encoding: "utf-8"
favicon: favicon.ico 

repository: nangongyibin7219/nangongyibin7219.github.io
github_url: https://github.com/nangongyibin7219
url: http://nangongyibin7219.github.io
enforce_ssl: ityouknow.com

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
   coderay_line_numbers:  nil

# Pagination
paginate: 12
paginate_path: 'page:num'

# Navigation. top menu list
menus:

  -
    href: /zsxq.html
    label: 星球
    target: _self

  -
    href: /gitchat.html
    label: Chat
    target: _self

  -
    href: /geektime.html
    label: 极客
    target: _blank

  -
    href: /life.html
    label: 故事
    target: _self

  -
    href: /arch.html
    label: 架构
    target: _self

  -
    href: /link.html
    label: 友链
    target: _self



# Navigation. main menu list
navs:

  -
    href: /
    label: Home

  - 
    href: /Activity.html
    label: Android
    target: _self
    subnav:

       -
        subHref: /Activity.html
        subLabel: Activity

       -
        subHref: /other.html
        subLabel: Other



  -
    href: /Redis.html
    label: Java
    target: _self
    subnav:

      -
        subHref: /Redis.html
        subLabel: Redis

      -
        subHref: /mongodb.html
        subLabel: Mongodb


  -
    href: /archives.html
    label: Archives
    target: _self

  -
    href: /about.html
    label: About
    target: _self


# labels. my blog key words
labels:

  -
    href: /payment.html
    label: 支付     
    target: _self

  -
    href: /fastdfs.html
    label: FastDFS
    target: _blank

  -
    href: /mongodb.html
    label: MongoDB
    target: _blank

  -
    href: /docker.html
    label: Docker
    target: _blank

  -
    href: /open-source.html
    label: Code  
    target: _blank

  -
    href: /it.html
    label: IT 
    target: _blank

  -
    href: /python.html
    label: Python  
    target: _blank


# selected articles
classes:

  -
    href: /life.html
    name: 我的故事
    describe: 生活就是故事，故事就是生活

  -
    href: /arch.html
    name: 架构师之路
    describe: 一个架构师的自我修养

  -
    href: /java.html
    name: Java 系列文章
    describe: Java 之根基，Java 程序员必学


# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, MySQL, Oracle, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, NodeJS, ExpressJS, MongoDB, Redis, PHP,  Boostrap]
skill_mobile_app_keywords: [vuejs, hyhird app]


# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: ityouknow
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: ityouknow
    repo: blog-comments
    oauth:
        client_id: 61bfc53d957e74e78f8f
        client_secret: 31c61e66cdcc9ada8db2267ee779d0bdafac434c
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: ityouknow
    repo: blog-comments
    clientID: 61bfc53d957e74e78f8f
    clientSecret: 31c61e66cdcc9ada8db2267ee779d0bdafac434c
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true