     # Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  南宫燚滨
subtitle: 耕耘不断，晟功在望
name: 南宫燚滨 
email: nangongyibin@gmail.com
description: 人生最幸福的四件事：有人信你、有人爱你、有人帮你、有人懂你。遇见不论早晚，真心才能相伴；朋友不论远近，懂得才有温暖。轰轰烈烈的，未必是真心；默默无声的，未必是无心。把一切交给时间，总会有答案。平淡中的相守，才最珍贵；简单中的拥有，才最心安！说的再好不如做的好。感恩生命中信我、爱我、懂我、帮我的人。
keywords: 南宫燚滨,Android
encoding: "utf-8"
favicon: favicon.ico 

repository: nangongyibin/nangongyibin.github.io
github_url: https://github.com/nangongyibin
url: http://all.nangongyibin.com
enforce_ssl: nangongyibin.com

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
   coderay_line_numbers:  nil

# Pagination
paginate: 12
paginate_path: 'page:num'

# Navigation. top menu list
menus:

  -
    href: /link.html
    label: 友链
    target: _self



# Navigation. main menu list
navs:

  -
    href: /
    label: Home

  - 
    href: /activity.html
    label: Android
    target: _self
    subnav:

       -
        subHref: /activity.html
        subLabel: Activity


       -
        subHref: /fragment.html
        subLabel: Fragment


       -
        subHref: /broadcastreceiver.html
        subLabel: 广播接收者
        

       -
        subHref: /service.html
        subLabel: 服务
        
       -
        subHref: /contentprovider.html
        subLabel: 内容提供者
        
        
       -
        subHref: /layout.html
        subLabel: 控件
        
       -
        subHref: /database.html
        subLabel: 数据库
        
       -
        subHref: /netlib.html
        subLabel: 网络库
 
       -
        subHref: /third-party-service.html
        subLabel: 第三方服务

       -
        subHref: /encryption.html
        subLabel: 加密

       -
        subHref: /exception.html
        subLabel: 异常
        
       -
        subHref: /interview.html
        subLabel: 面试题

       -
        subHref: /other.html
        subLabel: Other

  -
    href: /java-syntax.html
    label: Java
    target: _self
    subnav:
    
      -
        subHref: /java-syntax.html
        subLabel: Java语法
        
      -
        subHref: /mysql.html
        subLabel: MySQL
        
      -
        subHref: /git.html
        subLabel: Git

      -
        subHref: /springboot.html
        subLabel: SpringBoot
        
      -
        subHref: /ssh.html
        subLabel: SSH
          
  -
    href: /html.html
    label: Web
    target: _self
    subnav:
    
      -
        subHref: /html.html
        subLabel: HTML

      -
        subHref: /css.html
        subLabel: CSS
        
      -
        subHref: /javascript.html
        subLabel: JavaScript
        
      -
        subHref: /echarts.html
        subLabel: Echarts
        
      -
        subHref: /vue.html
        subLabel: Vue

      -
        subHref: /extjs.html
        subLabel: Extjs

  -
    href: /c.html
    label: C/C++
    target: _self


  -
    href: /linux.html
    label: Linux
    target: _self


  -
    href: /wok.html
    label: 知识网
    target: _self



#  -
#    href: /archives.html
#    label: Archives
#    target: _self

  -
    href: /about.html
    label: About
    target: _self


# labels. my blog key words
labels:

  -
    href: /open-source-page.html
    label: Code  
    target: _blank


# selected articles
classes:

  -
    href: /kotlin.html
    name: Kotlin
    describe: Android 官方开发语言

  -
    href: /flutter.html
    name: Flutter
    describe: Flutter
    


# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, MySQL]
skill_j2ee_keywords: [JSP]
skill_web_keywords: [HTML]
skill_mobile_app_keywords: [hyhird app]


# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
#
#


#
# https://disqus.com
disqus:
    username: nangongyibin
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: nangongyibin
    repo: nangongyibin.github.io
    oauth:
        client_id: b16fe83190c665c4af34
        client_secret: 58ba170c05de517687dc937948dbca53021f343e
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: nangongyibin
    repo: nangongyibin.github.io
    clientID: b16fe83190c665c4af34
    clientSecret: 58ba170c05de517687dc937948dbca53021f343e
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true